CREATE DATABASE retail_analytics;
USE retail_analytics;
SELECT * FROM final_dataset LIMIT 10;
SELECT age_group, count(*) AS total_customers FROM final_dataset GROUP BY age_group ORDER BY total_customers DESC;
SELECT age_group, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY age_group ORDER BY total_revenue DESC;
SELECT payment_method, COUNT(*) AS total_orders, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY payment_method ORDER BY total_orders DESC;
SELECT product_id, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY product_id ORDER BY total_revenue DESC LIMIT 10;
SELECT product_id, SUM(profit) AS total_profit FROM final_dataset GROUP BY product_id ORDER BY total_profit DESC LIMIT 10;
SELECT category, SUM(revenue) AS total_revenue, SUM(profit) AS total_profit, AVG(profit) AS avg_profit_per_order FROM final_dataset GROUP BY category ORDER BY total_profit DESC;
SELECT store_id, SUM(revenue) AS total_revenue, SUM(profit) AS total_profit, COUNT(*) AS total_orders, AVG(profit) AS avg_profit_per_order FROM final_dataset GROUP BY store_id ORDER BY total_profit DESC;
SELECT month_name, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY month_name ORDER BY MIN(month);
SELECT month_name, SUM(profit) AS total_profit FROM final_dataset GROUP BY month_name ORDER BY MIN(month);
SELECT month_name, COUNT(*) AS total_orders FROM final_dataset GROUP BY month_name ORDER BY MIN(month);
SELECT category, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY category ORDER BY total_revenue DESC;
SELECT category, SUM(profit) AS total_profit FROM  final_dataset GROUP BY category ORDER BY total_profit DESC;
SELECT category, AVG(profit) AS avg_profit_per_order FROM final_dataset GROUP BY category ORDER BY avg_profit_per_order DESC;
SELECT store_id, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY store_id ORDER BY total_revenue DESC;
SELECT store_id, SUM(profit) AS total_profit FROM final_dataset GROUP BY store_id ORDER BY total_profit DESC;
SELECT store_id, COUNT(*) AS total_orders FROM final_dataset GROUP BY store_id ORDER BY total_orders DESC;
SELECT payment_method, COUNT(*) AS total_orders FROM final_dataset GROUP BY payment_method ORDER BY total_orders DESC;
SELECT payment_method, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY payment_method ORDER BY total_revenue DESC;
SELECT is_high_margin, COUNT(*) AS total_orders, SUM(revenue) AS total_revenue, SUM(profit) AS total_profit FROM final_dataset GROUP BY is_high_margin;
SELECT is_high_footfall, COUNT(*) AS total_orders, SUM(revenue) AS total_revenue, SUM(profit) AS total_profit FROM final_dataset GROUP BY is_high_footfall;
SELECT order_status, COUNT(*) AS total_orders FROM final_dataset GROUP BY order_status ORDER BY total_orders DESC;
SELECT order_id, profit FROM final_dataset ORDER BY profit DESC;
SELECT category, month_name, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY category, month_name ORDER BY category, MIN(month);
SELECT store_id, month_name, SUM(revenue) AS total_revenue FROM final_dataset GROUP BY store_id, month_name ORDER BY store_id, MIN(month);
SELECT category, payment_method, SUM(profit) AS total_profit FROM final_dataset GROUP BY category, payment_method ORDER BY category, total_profit DESC;
